### PR TITLE
Use GPRIndex.rand in some more places

### PR DESCRIPTION
**Pull request by shigoel**
### Description:

Use `GPRIndex.rand` for a few instructions that I overlooked in #103

### Testing:

`make all` succeeds on my M3.

### License:

By submitting this pull request, I confirm that my contribution is
made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bollu** [comment]
I grepped for `rg "(Rd|Rn) := ← BitVec.rand 5"` on top of this commit, and found the following occurrences. I don't know how many are legit. @shigoel , maybe you could take a quick look and see if any of these need to be updated?

```lean
➜  LNSym git:(more_x18_fixes) rg "(Rd|Rn) := ← BitVec.rand 5" --context 6
Arm/Insts/DPSFP/Crypto_aes.lean
105-----------------------------------------------------------------------
106-
107-def Crypto_aes_cls.aese.rand : IO (Option (BitVec 32)) := do
108-  let (inst : Crypto_aes_cls) :=
109-    { size := 0b00#2,
110-      opcode := 0b00100#5,
111:      Rn := ← BitVec.rand 5,
112:      Rd := ← BitVec.rand 5
113-    }
114-  pure (some inst.toBitVec32)
115-
116-def Crypto_aes_cls.aesmc.rand : IO (Option (BitVec 32)) := do
117-  let (inst : Crypto_aes_cls) :=
118-    { size := 0b00#2,
119-      opcode := 0b00110#5,
120:      Rn := ← BitVec.rand 5,
121:      Rd := ← BitVec.rand 5
122-    }
123-  pure (some inst.toBitVec32)
124-
125-/-- Generate random instructions of Crypto_aes_cls class. -/
126-def Crypto_aes_cls.rand : List (IO (Option (BitVec 32))) :=
127-  [ Crypto_aes_cls.aese.rand,

Arm/Insts/DPSFP/Advanced_simd_permute.lean
67-  else
68-    let (inst : Advanced_simd_permute_cls) :=
69-      { Q := Q,
70-        size := size,
71-        Rm := ← BitVec.rand 5,
72-        opcode := 0b010#3,
73:        Rn := ← BitVec.rand 5,
74:        Rd := ← BitVec.rand 5
75-      }
76-    pure (some (inst.toBitVec32))
77-
78-partial def Advanced_simd_permute_cls.trn2.rand : IO (Option (BitVec 32)) := do
79-  let size := ← BitVec.rand 2
80-  let Q := ← BitVec.rand 1
--
83-  else
84-    let (inst : Advanced_simd_permute_cls) :=
85-      { Q := Q,
86-        size := size,
87-        Rm := ← BitVec.rand 5,
88-        opcode := 0b110#3,
89:        Rn := ← BitVec.rand 5,
90:        Rd := ← BitVec.rand 5
91-      }
92-    pure (some (inst.toBitVec32))
93-
94-/-- Generate random instructions of Advanced_simd_permute class. -/
95-def Advanced_simd_permute_cls.rand : List (IO (Option (BitVec 32))) :=
96-  [ Advanced_simd_permute_cls.trn1.rand,

Arm/Insts/DPSFP/Advanced_simd_three_different.lean
83-    let (inst : Advanced_simd_three_different_cls) :=
84-      { Q := ← BitVec.rand 1,
85-        U := 0b0#1,
86-        size := size,
87-        Rm := ← BitVec.rand 5,
88-        opcode := 0b1110#4,
89:        Rn := ← BitVec.rand 5,
90:        Rd := ← BitVec.rand 5
91-      }
92-    pure (some (inst.toBitVec32))
93-
94-/-- Generate random instructions of Advanced_simd_three_different class. -/
95-def Advanced_simd_three_different_cls.rand : List (IO (Option (BitVec 32))) :=
96-  [Advanced_simd_three_different_cls.pmull.rand]

Arm/Insts/DPSFP/Advanced_simd_shift_by_immediate.lean
103-    let (inst : Advanced_simd_shift_by_immediate_cls) :=
104-      { Q := Q,
105-        U := ← BitVec.rand 1,
106-        immh := immh,
107-        immb := ← BitVec.rand 3,
108-        opcode := opcode,
109:        Rn := ← BitVec.rand 5,
110:        Rd := ← BitVec.rand 5
111-      }
112-    pure (some inst.toBitVec32)
113-
114-partial def Advanced_simd_shift_by_immediate_cls.shl.rand
115-  : IO (Option (BitVec 32)) := do
116-  let Q := ← BitVec.rand 1
--
121-    let (inst : Advanced_simd_shift_by_immediate_cls) :=
122-      { Q := Q,
123-        U := 0b0#1,
124-        immh := immh,
125-        immb := ← BitVec.rand 3,
126-        opcode := 0b01010#5,
127:        Rn := ← BitVec.rand 5,
128:        Rd := ← BitVec.rand 5
129-      }
130-    pure (some inst.toBitVec32)
131-
132-/-- Generate random instructions of Advanced_simd_shift_by_immediate_cls class. -/
133-def Advanced_simd_shift_by_immediate_cls.rand : List (IO (Option (BitVec 32))) :=
134-[ Advanced_simd_shift_by_immediate_cls.shl.rand,               -- SHL

Arm/Insts/DPSFP/Advanced_simd_table_lookup.lean
76-  let (inst : Advanced_simd_table_lookup_cls) :=
77-    { Q := ← BitVec.rand 1,
78-      op2 := 0b00#2,
79-      Rm := ← BitVec.rand 5,
80-      len := ← BitVec.rand 2,
81-      op := ← BitVec.rand 1,
82:      Rn := ← BitVec.rand 5,
83:      Rd := ← BitVec.rand 5
84-    }
85-  pure (some (inst.toBitVec32))
86-
87-/-- Generate random instructions of Advanced_simd_table_lookup class. -/
88-def Advanced_simd_table_lookup_cls.rand : List (IO (Option (BitVec 32))) :=
89-  [ Advanced_simd_table_lookup_cls.tbl.rand ]

Arm/Insts/DPSFP/Advanced_simd_scalar_copy.lean
41-    Advanced_simd_scalar_copy_cls.dup.rand
42-  else
43-    let (inst : Advanced_simd_scalar_copy_cls) :=
44-      { op := 0b0#1,
45-        imm5 := imm5,
46-        imm4 := 0b0000#4,
47:        Rn := ← BitVec.rand 5,
48:        Rd := ← BitVec.rand 5
49-      }
50-    pure (some inst.toBitVec32)
51-
52-/-- Generate random instructions of Advanced_simd_scalar_copy class. -/
53-def Advanced_simd_scalar_copy_cls.rand : List (IO (Option (BitVec 32))) :=
54-  [ Advanced_simd_scalar_copy_cls.dup.rand ]

Arm/Insts/DPSFP/Advanced_simd_scalar_shift_by_immediate.lean
85-  else
86-    let (inst : Advanced_simd_scalar_shift_by_immediate_cls) :=
87-      { U := ← BitVec.rand 1,
88-        immh := immh,
89-        immb := ← BitVec.rand 3,
90-        opcode := opcode,
91:        Rn := ← BitVec.rand 5,
92:        Rd := ← BitVec.rand 5
93-      }
94-    pure (some inst.toBitVec32)
95-
96-partial def Advanced_simd_scalar_shift_by_immediate_cls.shl.rand
97-  : IO (Option (BitVec 32)) := do
98-  let immh := ← BitVec.rand 4
--
101-  else
102-    let (inst : Advanced_simd_scalar_shift_by_immediate_cls) :=
103-      { U := 0b0#1,
104-        immh := immh,
105-        immb := ← BitVec.rand 3,
106-        opcode := 0b01010#5,
107:        Rn := ← BitVec.rand 5,
108:        Rd := ← BitVec.rand 5
109-      }
110-    pure (some inst.toBitVec32)
111-
112-/-- Generate random instructions of Advanced_simd_scalar_shift_by_immediate_cls class. -/
113-def Advanced_simd_scalar_shift_by_immediate_cls.rand : List (IO (Option (BitVec 32))) :=
114-[ Advanced_simd_scalar_shift_by_immediate_cls.shl.rand,               -- SHL

Arm/Insts/DPSFP/Advanced_simd_two_reg_misc.lean
120-partial def Advanced_simd_two_reg_misc_cls.rev64_16.rand : IO (Option (BitVec 32)) := do
121-  let (inst : Advanced_simd_two_reg_misc_cls) :=
122-    { Q := ← BitVec.rand 1,
123-      U := ← pure 0b0#1,
124-      size := ← BitVec.rand 2,
125-      opcode := ← BitVec.rand 5 (lo := 0) (hi := 1), -- 0b00000 and 0b00001
126:      Rn := ← BitVec.rand 5,
127:      Rd := ← BitVec.rand 5 }
128-  let esize := 8 <<< inst.size.toNat
129-  let container_size := 64 >>> ((lsb inst.opcode 0) ++ inst.U).toNat
130-  if container_size <= esize then
131-    -- Keep generating random instructions until a legal one is encountered.
132-    Advanced_simd_two_reg_misc_cls.rev64_16.rand
133-  else
--
136-partial def Advanced_simd_two_reg_misc_cls.rev32.rand : IO (Option (BitVec 32)) := do
137-  let (inst : Advanced_simd_two_reg_misc_cls) :=
138-    { Q := ← BitVec.rand 1,
139-      U := ← pure 0b1#1,
140-      size := ← BitVec.rand 2,
141-      opcode := ← pure 0b00000#5,
142:      Rn := ← BitVec.rand 5,
143:      Rd := ← BitVec.rand 5 }
144-  let esize := 8 <<< inst.size.toNat
145-  let container_size := 64 >>> ((lsb inst.opcode 0) ++ inst.U).toNat
146-  if container_size <= esize then
147-    -- Keep generating random instructions until a legal one is encountered.
148-    Advanced_simd_two_reg_misc_cls.rev32.rand
149-  else

Arm/Insts/DPSFP/Advanced_simd_three_same.lean
128-  let (inst : Advanced_simd_three_same_cls) :=
129-    { Q := Q,
130-      U := ← BitVec.rand 1,
131-      size := size,
132-      Rm := ← BitVec.rand 5,
133-      opcode := ← pure 0b10000#5,
134:      Rn := ← BitVec.rand 5,
135:      Rd := ← BitVec.rand 5 }
136-  pure (inst.toBitVec32)
137-
138-def Advanced_simd_three_same_cls.logic.rand : IO (Option (BitVec 32)) := do
139-  let (inst : Advanced_simd_three_same_cls) :=
140-    { Q := ← BitVec.rand 1,
141-      U := ← BitVec.rand 1,
142-      size := ← BitVec.rand 2,
143-      Rm := ← BitVec.rand 5,
144-      opcode := ← pure 0b00011#5,
145:      Rn := ← BitVec.rand 5,
146:      Rd := ← BitVec.rand 5 }
147-  pure (inst.toBitVec32)
148-
149-/-- Generate random instructions of Advanced_simd_three_same class. -/
150-def Advanced_simd_three_same_cls.rand : List (IO (Option (BitVec 32))) :=
151-  [ Advanced_simd_three_same_cls.binary.rand,
152-    Advanced_simd_three_same_cls.logic.rand ]

Arm/Insts/DPSFP/Advanced_simd_copy.lean
147-  else
148-    let (inst : Advanced_simd_copy_cls) :=
149-      { Q := Q,
150-        op := 0b0#1,
151-        imm5 := imm5,
152-        imm4 := 0b0000#4,
153:        Rn := ← BitVec.rand 5,
154:        Rd := ← BitVec.rand 5
155-      }
156-    pure (inst.toBitVec32)
157-
158-partial def Advanced_simd_copy_cls.dup_general.rand : IO (Option (BitVec 32)) := do
159-  let Q := ← BitVec.rand 1
160-  let imm5 := ← BitVec.rand 5
--
166-      { Q := Q,
167-        op := 0b0#1,
168-        imm5 := imm5,
169-        imm4 := 0b0001#4,
170-        -- GPR Rn is a source operand for this instruction.
171-        Rn := ← GPRIndex.rand,
172:        Rd := ← BitVec.rand 5
173-      }
174-    pure (inst.toBitVec32)
175-
176-partial def Advanced_simd_copy_cls.ins_element.rand : IO (Option (BitVec 32)) := do
177-  let imm5 := ← BitVec.rand 5
178-  let size := lowest_set_bit imm5
--
181-  else
182-    let (inst : Advanced_simd_copy_cls) :=
183-      { Q := 0b1#1,
184-        op := 0b1#1,
185-        imm5 := imm5,
186-        imm4 := ← BitVec.rand 4,
187:        Rn := ← BitVec.rand 5,
188:        Rd := ← BitVec.rand 5
189-      }
190-    pure (inst.toBitVec32)
191-
192-partial def Advanced_simd_copy_cls.ins_general.rand : IO (Option (BitVec 32)) := do
193-  let imm5 := ← BitVec.rand 5
194-  let size := lowest_set_bit imm5
--
199-      { Q := 0b1#1,
200-        op := 0b0#1,
201-        imm5 := imm5,
202-        imm4 := 0b0011#4,
203-        -- GPR Rn is a source operand for this instruction.
204-        Rn := ← GPRIndex.rand,
205:        Rd := ← BitVec.rand 5
206-      }
207-    pure (inst.toBitVec32)
208-
209-partial def Advanced_simd_copy_cls.smov.rand : IO (Option (BitVec 32)) := do
210-  let Q := ← BitVec.rand 1
211-  let imm5 := ← BitVec.rand 5
--
217-  else
218-    let (inst : Advanced_simd_copy_cls) :=
219-      { Q := Q,
220-        op := 0b0#1,
221-        imm5 := imm5,
222-        imm4 := 0b0101#4,
223:        Rn := ← BitVec.rand 5,
224-        -- GPR Rd is the destination operand for this instruction.
225-        Rd := ← GPRIndex.rand
226-      }
227-    pure (inst.toBitVec32)
228-
229-partial def Advanced_simd_copy_cls.umov.rand : IO (Option (BitVec 32)) := do
--
237-  else
238-    let (inst : Advanced_simd_copy_cls) :=
239-      { Q := Q,
240-        op := 0b0#1,
241-        imm5 := imm5,
242-        imm4 := 0b0111#4,
243:        Rn := ← BitVec.rand 5,
244-        -- GPR Rd is the destination operand for this instruction.
245-        Rd := ← GPRIndex.rand```

**Comment by shigoel** [comment]
Difficult to check from this log unfortunately. We use `BitVec.rand 5` for SIMD&FP regs too.

**Comment by bollu** [comment]
@shigoel that's unfortunate. Could you point me to where I would find the spec that tells me which regs are of what register type?

**Comment by shigoel** [comment]
Searching for `read/write_gpr` and seeing whether we use `GPRIndex.rand` to generate random indices for those instructions would work better (which is what I did previously, but maybe only in some subdirs of `Arm`).

**Comment by bollu** [comment]
Feel invited to merge this @shigoel .

**Comment by pennyannn** [comment]
I have done a manual check and it seems all cases are covered. I did the following:

Look under Arm/Insts:
1. BR and LDST are not cosim tested, so they don't need to be checked.
2. Check all instruction files in DPI, DPR and DPSFP. 
3. DPI and DPR are about GPRs, so all BitVec.rand 5 should be turned into GPRIndex.rand
4. DPSFP is slightly more complicated because one has to distinguish between SFP and GPR, but most of the instructions only involves SFP and only a few need to be addressed. (Look for string `_gpr` (this will include both `read_gpr` and `write_gpr`)).

Seems good to me.

**Review by pennyannn — APPROVED** [review]

**Pull request merged**
