### PR TITLE
feat: Aarch64 runner

### PR DESCRIPTION
**Pull request by bollu**
If this works, this can be merged after #77 to enable cosim in github CI.

### CODE REVIEW

**Comment by shigoel** [comment]
Amd64? Do you mean Arm64/Aarch64?

**Comment by bollu** [comment]
@shigoel Feel invited to hit merge, the CI action does the right thing now :)

**Review by shigoel — APPROVED** [review]
Thank you!

**Comment by shigoel** [comment]
@bollu Thanks for submitting the issue: https://github.com/leanprover/lean-action/issues/83 
Can we create one of our own that uses `leanprover/lean-action` when the above is resolved?

**Pull request merged**
