### PR TITLE
refactor: use lean-action in makefile.yml CI workflow

### LINKED ISSUE #82: Switch back to using leanprover/lean-action once MacOS runner is fixed
We switched to using MacOS runner in https://github.com/leanprover/LNSym/pull/78, in order to allow to run `aarch64` in CI. 

We're waiting for https://github.com/leanprover/lean-action/issues/83 to be fixed via the PR that switches to `elan-init.sh` (https://github.com/leanprover/lean-action/pull/84) to go back to using `leanprover/lean-action`.

### PR DESCRIPTION
**Pull request by austinletson**
### Description:

`lean-action` now supports the macOS runner so you can now use it in makefile.yml

### License:

By submitting this pull request, I confirm that my contribution is
made under the terms of the Apache 2.0 license.

Closes #82

### CODE REVIEW

**Comment by austinletson** [comment]
Hi @bollu. You may want to change this PR or create a new one based on what you need, but with the latest release, lean-action now supports macOS runners.

There is one thing I wanted to flag after looking at this. By default, lean-action will run `lake build`. Is this redundant since you also run `lake build` in the Makefile? Note you can still use lean-action to set up Elan without running `lake build` by using the `auto-config: false` input:

```yml
  uses: leanprover/lean-action@v1
  with:
    auto-config: false
```

**Comment by bollu** [comment]
@austinletson thank you very much :) If you could add the line 

```lean
 with:
    auto-config: false
```

to the PR, @shigoel can merge this in tomorrow ^_^

**Comment by austinletson** [comment]
> @austinletson thank you very much :) If you could add the line
> 
> ```lean
>  with:
>     auto-config: false
> ```
> 
> to the PR, @shigoel can merge this in tomorrow ^_^

Done!

**Comment by bollu** [comment]
Thanks! @shigoel I think this is ready for "workflow approval"

**Comment by shigoel** [comment]
Thank you so much, @austinletson!

**Review by shigoel — APPROVED** [review]

**Pull request merged**
