### PR TITLE
chore: bump toolchain to nightly-2024-10-07

### PR DESCRIPTION
**Pull request by alexkeizer**
### Description:

Bumps the toolchain to the latest nightly. Mostly in the (unlikely) hope that some of our `instantiateMVars` performance woes might disappear.

### Testing:

What tests have been run? Did `make all` succeed for your changes? Was
conformance testing successful on an Aarch64 machine? Yes

### License:

By submitting this pull request, I confirm that my contribution is
made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by alexkeizer** [comment]
@bollu the traces for the CSE tests changed. I've accepted the new trace somewhat blindly; could you confirm the difference is benign?

**Comment by bollu** [comment]
Yep, LGTM!

**Comment by shigoel** [comment]
FYI: https://github.com/draperlaboratory/ELFSage/pull/15 where the toolchain is `leanprover/lean4:nightly-2024-10-07`

While that's upstreamed, we can use [my fork](https://github.com/shigoel/ELFSage) of ELFSage.

**Comment by shigoel** [comment]
FYI: https://github.com/draperlaboratory/ELFSage/pull/15 got merged.

**Pull request merged**
