### PR TITLE
refactor: rename `Reflect` folder to `Sym`, move `SymContext` to `Sym/Context`

### PR DESCRIPTION
**Pull request by alexkeizer**
### Description:

Stacked on #182.

The new name makes more sense, since this is where I've been storing various components of the `sym_n` tactic implementation, even if they're not really doing reflection

### Testing:

What tests have been run? Did `make all` succeed for your changes? Was
conformance testing successful on an Aarch64 machine? Yes

### License:

By submitting this pull request, I confirm that my contribution is
made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by alexkeizer** [comment]
@shigoel an easy one, this just moves around some files. Rebased and ready for review

**Comment by bollu** [comment]
LGTM

**Comment by shigoel** [comment]
@alexkeizer Incoming conflicts.

**Comment by alexkeizer** [comment]
@shigoel I merged main

**Review by shigoel — APPROVED** [review]

**Pull request merged**
